### ISSUE TITLE
db hint

### ISSUE THREAD

**Issue by vitaly-t** [walkertd/roomba-follower#1]
If you want rows as arrays of values, you can simply do:

```js
db.any({text: 'select * from recordings', rowMode: 'array'})
```

**Comment by walkertd** [comment]
Thanks for the hint!  I knew there must have been a way to do that with pg-promise the framework.

This is my first time using Javascript for more than basic webpage stuff (and that was 10+ years ago) so I'm learning how to use Javascript, NodeJS and all the various packages for the first time.  I really appreciate the help!
